io_groups:
  io_group_0:
    hostname: pacman0.local
    uarts:
      0:
        - chip_id: 1000
          dn: 0        # direction toward FPGA (root's FPGA-facing port)
          up: 1        # direction toward next ASIC in chain
        - chip_id: 1001
          dn: 1        # points back toward previous ASIC / FPGA
          up: 2
        - chip_id: 1002
          dn: 2
          up: 3
        - chip_id: 1003
          dn: 3
          up: null     # end of chain
      1:
        - chip_id: 1100
          dn: 0
          up: 1
        - chip_id: 1101
          dn: 1
          up: 2
        - chip_id: 1102
          dn: 2
          up: 3
        - chip_id: 1103
          dn: 3
          up: null

  io_group_1:
    hostname: pacman1.local
    uarts:
      0:
        - chip_id: 2000
          dn: 0
          up: 1
        - chip_id: 2001
          dn: 1
          up: 2
        - chip_id: 2002
          dn: 2
          up: 3
        - chip_id: 2003
          dn: 3
          up: null
      1:
        - chip_id: 2100
          dn: 2
          up: 3
        - chip_id: 2101
          dn: 3
          up: 0
        - chip_id: 2102
          dn: 0
          up: 1
        - chip_id: 2103
          dn: 1
          up: null
