network:
  - io_group: 1
    hostname: pacman-srv1.local
    port: 5555
    timeout_ms: 2000
    first_io_chan: 0x100
    uart_mask: 0xF
  - io_group: 2
    hostname: pacman-srv2.local
    port: 5555
    timeout_ms: 2000
    first_io_chan: 0x200
    uart_mask: 0xFF
