#
#
# *014 e 013 e 012 e 011
#

parameters:
  ports:      [n, w, s, e]
  directions: [[0,1], [-1,0], [0,-1], [1,0]]

chips:
  - chip_id: 14
    w: fpga
    e: 13
  - chip_id: 13
    e: 12
  - chip_id: 12
    e: 11
  - chip_id: 11

