#
# 013
#  +
# 012
#  +
# 011+003
#  *
#

parameters:
  ports:      [n, w, s, e]
  directions: [[0,1], [-1,0], [0,-1], [1,0]]

chips:
  - chip_id: 11
    w: fpga
    n: 12
    e: 3
  - chip_id: 12
    n: 13
  - chip_id: 13
    w: 4
  - chip_id: 3
  - chip_id: 4