library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;
library work;
use work.common.all;
use work.atc_pkg.all;

entity atc_unit is
  port (
    -- clock and active-high reset
    ACLK                  : in std_logic; -- fast clock
    RST_I                 : in std_logic;
    -- UART clock generated by SoC:
    UCLK_I                : in std_logic; -- slow clock

    -- REGBUS interface
    S_REGBUS_RB_RADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
    S_REGBUS_RB_RDATA	  : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
    S_REGBUS_RB_RUPDATE   : in  std_logic;
    S_REGBUS_RB_RACK      : out std_logic;

    S_REGBUS_RB_WUPDATE   : in  std_logic;
    S_REGBUS_RB_WADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
    S_REGBUS_RB_WDATA	  : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
    S_REGBUS_RB_WACK      : out std_logic;

    -- front panel LEMO inputs:
    LEMO_A_I              : in std_logic;
    LEMO_B_I              : in std_logic;

    TIMESTAMP_O           : out std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0);
    UCLK_O                : out std_logic;
    G_O                   : out std_logic_vector(C_NUM_TILE-1 downto 0);
    H_O                   : out std_logic_vector(C_NUM_TILE-1 downto 0)
    );
end atc_unit;

architecture behaviour of atc_unit is
  component atc_registers is
    port (
      CLK_I : in std_logic;
      RST_I : in std_logic;
      S_REGBUS_RB_RUPDATE : in  std_logic;
      S_REGBUS_RB_RADDR	: in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
      S_REGBUS_RB_RDATA	: out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      S_REGBUS_RB_RACK    : out std_logic;
      S_REGBUS_RB_WUPDATE : in  std_logic;
      S_REGBUS_RB_WADDR	: in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
      S_REGBUS_RB_WDATA	: in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      S_REGBUS_RB_WACK    : out std_logic;
      UPDATE_CONFIGS_O    : out std_logic;  -- CDC
      UPDATE_COUNTS_O     : out std_logic;  -- CDC 
      POKE_C_O            : out std_logic;  -- CDC
      MASK_C_O            : out std_logic_vector(C_NUM_TILE-1 downto 0); -- CDC
      POKE_D_O            : out std_logic;  -- CDC 
      MASK_D_O            : out std_logic_vector(C_NUM_TILE-1 downto 0); -- CDC
      CONFIG_O            : out atc_config_t; 
      STATUS_I            : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      TIMESTAMP_I         : in  std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0)    
      );
  end component;

  signal clk : std_logic;
  signal rst : std_logic;

  signal update_configs : std_logic;
  signal busy_configs   : std_logic;
  signal update_counts  : std_logic;
  signal poke_c         : std_logic;
  signal mask_c         : std_logic_vector(C_NUM_TILE-1 downto 0);
  signal poke_d         : std_logic;
  signal mask_d         : std_logic_vector(C_NUM_TILE-1 downto 0);


begin
  clk <= ACLK;
  rst <= RST_I;


  TIMESTAMP_O <= (others => '0');
  UCLK_O <= UCLK_I;
  G_O <= (others => LEMO_A_I);
  H_O <= (others => LEMO_B_I);

  uut0: atc_registers port map (
    CLK_I               => clk,
    RST_I               => rst,
    S_REGBUS_RB_RUPDATE =>     S_REGBUS_RB_RUPDATE,
    S_REGBUS_RB_RADDR   =>     S_REGBUS_RB_RADDR,
    S_REGBUS_RB_RDATA   =>     S_REGBUS_RB_RDATA,
    S_REGBUS_RB_RACK    =>     S_REGBUS_RB_RACK,
    S_REGBUS_RB_WUPDATE =>     S_REGBUS_RB_WUPDATE,
    S_REGBUS_RB_WADDR   =>     S_REGBUS_RB_WADDR,
    S_REGBUS_RB_WDATA   =>     S_REGBUS_RB_WDATA,
    S_REGBUS_RB_WACK    =>     S_REGBUS_RB_WACK,
    UPDATE_CONFIGS_O    => update_configs,
    UPDATE_COUNTS_O     => update_counts,
    POKE_C_O            => poke_c,
    MASK_C_O            => mask_c,
    POKE_D_O            => poke_d,
    MASK_D_O            => mask_d,
    STATUS_I            => x"1234ABCD",
    TIMESTAMP_I         => x"AAAABBBBCCCCDDDD"
  );



end behaviour;
