set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[10]}]

set_property PACKAGE_PIN J16  [get_ports {gpio_0_tri_io[0]}]
set_property PACKAGE_PIN G21  [get_ports {gpio_0_tri_io[1]}]
set_property PACKAGE_PIN P18  [get_ports {gpio_0_tri_io[2]}]
set_property PACKAGE_PIN P17  [get_ports {gpio_0_tri_io[3]}]
set_property PACKAGE_PIN K15  [get_ports {gpio_0_tri_io[4]}]
set_property PACKAGE_PIN L21  [get_ports {gpio_0_tri_io[5]}]
set_property PACKAGE_PIN P21  [get_ports {gpio_0_tri_io[6]}]
set_property PACKAGE_PIN P20  [get_ports {gpio_0_tri_io[7]}]
set_property PACKAGE_PIN L22  [get_ports {gpio_0_tri_io[8]}]
set_property PACKAGE_PIN R19  [get_ports {gpio_0_tri_io[9]}]
set_property PACKAGE_PIN T19  [get_ports {gpio_0_tri_io[10]}]

set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
